name: cpmolgan
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=20.1.1=py36_1
  - python=3.6.10
  - h5py=2.10.0
  - hdf5=1.10.6
  - numpy==1.17.0
  - pandas=0.22.0
  - jupyter=1.0.0
  - notebook=6.0.3
  - keras-applications=1.0.8
  - keras-preprocessing==1.1.2
  - mkl=2020.1
  - rdkit=2018.09.1
  - scipy=1.5.0
  - tk=8.6.10
  - tqdm=4.47.0
  - scikit-learn=0.23.1
  - seaborn=0.10.1
  - networkx=2.5.1
  - umap-learn
  - pip:
    - selfies==0.2.4